#!/bin/bash

echo "=== dscli v0.5.4 会话统计信息显示优化演示 ==="
echo ""
echo "优化前的显示格式（三行）："
echo "⏱️  会话用时: 30.0s"
echo "💰  会话花费: CNY 4.50"
echo "💳  当前余额: CNY 95.50"
echo ""
echo "优化后的显示格式（一行）："
echo "⏱️ 30.0s  💰 CNY 4.50  💳 CNY 95.50"
echo ""
echo "低余额提醒（一行）："
echo "⏱️ 30.0s  💰 CNY 95.00  💳 CNY 5.00  ⚠️ 余额较低，请及时充值！"
echo ""
echo "=== 优势 ==="
echo "1. 更简洁：从三行减少到一行"
echo "2. 更紧凑：节省屏幕空间"
echo "3. 更直观：图标+数据，无需文字说明"
echo "4. 更低调：不占用过多注意力"
echo ""
echo "=== 使用方式 ==="
echo "会话结束后自动显示，无需额外配置"
echo ""
echo "=== 图标说明 ==="
echo "⏱️  - 用时"
echo "💰  - 花费"
echo "💳  - 余额"
echo "⚠️  - 低余额提醒"